# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: zamazzal <zouhir.amazzal@gmail.com>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/12/06 05:33:57 by zamazzal          #+#    #+#              #
#    Updated: 2018/12/06 23:52:38 by zamazzal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM debian

RUN apt update
RUN apt upgrade -y
RUN apt install gcc -y
RUN apt install vim -y
RUN apt install nano -y
RUN apt install emacs -y
RUN apt install git -y
